server:
  port: 8085
spring:
  application:
    name: user-server
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/shixun?useUnicode=true&characterEncoding=utf-8
    username: root
    password: 999123
    driver-class-name: com.mysql.jdbc.Driver
  redis:
    host: 192.168.138.128
  rabbitmq:
    host: 192.168.138.128
    username: admin
    password: admin
    virtual-host: /
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:10086/eureka
  instance:
    prefer-ip-address: true
    ip-address: 127.0.0.1
    instance-id: ${eureka.instance.ip-address}.${server.port}
    lease-renewal-interval-in-seconds: 3
    lease-expiration-duration-in-seconds: 10

mybatis:
  type-aliases-package: com.anming.item.pojo