server:
  port: 10010
spring:
  application:
    name: zuul-server
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:10086/eureka
    registry-fetch-interval-seconds: 5
  instance:
    prefer-ip-address: true
    ip-address: 127.0.0.1
    instance-id: ${spring.application.name}:${server.port}
zuul:
  prefix: /api # 添加路由前缀
  routes:
    item-server:
      path: /item/** # 将商品微服务映射到/item/**
    upload-server:
      path: /upload/**
    search-server:
      path: /search/** # 将商品微服务映射到/item/**
    details-server:
      path: /details/**
    user-server:
      path: /user/**
    auth-server:
      path: /auth/**
    cart-server:
      path: /cart/**
    payment-server:
      path: /order/**
  add-host-header: true
  sensitive-headers=:
ly:
  filter:
    allowPaths:
      - /api/search
      - /api/user
      - /api/item
      - /api/cart
      - /api/order
ribbon:
  ConnectTimeout: 5000 # 连接超时时间(ms)
  ReadTimeout: 5000 # 通信超时时间(ms)
  OkToRetryOnAllOperations: true # 是否对所有操作重试
  MaxAutoRetriesNextServer: 1 # 同一服务不同实例的重试次数
  MaxAutoRetries: 1 # 同一实例的重试次数
